### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by nathantreid** [Sendoushi/babel-plugin-remove-code#1]
First, thanks for making this plugin - it's really awesome! I'd like to make a PR to support removing identifiers and member expressions, but I'm not sure what the project's license is.
Identifier support would strip this:
```js
if (stripA) {}
```
Member expression support would strip these:
```js
if (strip.prop) {}

if (strip['prop']) {}
```
Thanks!

**Comment by Sendoushi** [comment]
Hey! I haven't been on this repo for awhile. I need to figure out some time to get back to open source and a project that motivates to do so ehehe.
Feel completely free to do whatever, I'll definitely accept PRs and the license is "free as in salt water".

**Comment by nathantreid** [comment]
A lot of organizations require an explicit license in order to use 3rd party packages. Do you mind adding / would you accept a PR to add a license (MIT, ISC, UNLICENSE, etc) on your behalf?

**Comment by akanix42** [comment]
Added in #3.
