### ISSUE TITLE
(feature request) Remove code between comment patterns

### ISSUE THREAD

**Issue by fnmendez** [Sendoushi/babel-plugin-remove-code#4]
Thank you!

I'd like to remove some `useEffect`s from my React app at build time. I use them for debugging stuff and I don't want them to reduce performance at production.

Is it possible to do it with this plugin as it is?

Does this plugin runs fine with the latest versions of babel (7.x)?

Thank you again

**Comment by iamajoe** [comment]
To be honest... No idea. I haven't used this for such a long time. I should probably just deprecate it.

**Comment by fnmendez** [comment]
I realized one can put the useEffects (and other hooks) under if conditions.

`if (process.env.NODE_ENV !== "production) { useEffect(...) }`

but I still love the idea to remove code with babel between some comment pattern.

Thank you for your quick response, cheers.
